version: '3.8'
services:
  nodejs-backend:
    image: nodejs-backend:01
    ports:
      - "8080:8080"
    env_file:
      - secret.env
    volumes:
      - .:/app
    command: ["node", "app.js"]
    environment:
      NODE_ENV: development
